<?php

define('SKYWORD_VERSION', 1); // Define the version of this api.

function skyword_init() {}

/**
 * Implements hook_services_resources
 */
function skyword_services_resources() {
  return array(
    'token' => array(
      'retrieve' => array(
        'help' => 'Returns authentication token from this site',
        'file' => array(
          'type' => 'inc', 
          'module' => 'token', 
          'name' => 'resources/token',
        ),
        'callback' => '_skyword_token_retrieve',
        'access callback' => '_skyword_access',
        'access arguments' => array('retrieve token'),
        'access arguments append' => TRUE,
      ), 
    ),
    'version' => array(
      'retrieve' => array(
        'help' => 'Returns the version of this site.',
        'file' => array(
          'type' => 'inc', 
          'module' => 'skyword', 
          'name' => 'resources/version'
        ),
        'callback' => '_skyword_version_retrieve',
        'access callback' => 'skyword_access',
        'access arguments' => array('retrieve version'),
        'access arguments append' => TRUE
      ),
    ),
    'taxonomies' => array(
      'index' => array(
        'help' => 'Returns a list of taxonomies',
        'file' => array(
          'type' => 'inc',
          'module' => 'skyword',
          'name' => 'resources/taxonomies',
        ),
        'callback' => '_skyword_taxonomies_index',
        'access callback' => 'skywrod_access',
        'access arguments' => array('index taxonomies'),
        'access arguments append' => TRUE,
        'args' => array(
          array(
            'name' => 'page',
            'type' => 'int',
            'description' => 'The starting page number. Default is 1',
            'source' => array('param' => 'page'),
            'optional' => TRUE,
          ),
          array(
            'name' => 'per_page',
            'type' => 'int',
            'description' => 'The number of entries to retrieve. Default is 250',
            'source' => array('param' => 'per_page'),
            'optional' => TRUE,
          ),
          array(
            'name' => 'fields',
            'type' => 'string',
            'description' => 'A comma separated list of fields to include.', 
            'source' => array('param' => 'fields'),
            'optional' => TRUE,
          ),
        ),
      ),
      'retrieve' => array(
        'help' => 'Returns a specific taxonomy',
        'file' => array(
          'type' => 'inc',
          'module' => 'skyword',
          'name' => 'resources/taxonomies',
        ),
        'callback' => '_skyword_taxonomies_retrieve',
        'access callback' => 'skyword_access',
        'access arguments' => array('retrieve taxonomy'),
        'access arguments append' => TRUE,
        'args' => array(
          array(
            'name' => 'id',
            'type' => 'int',
            'description' => 'The primary identifier of the taxonomy to retrieve',
            'source' => array('path' => '0'),
            'optional' => FALSE,
          ),
          array(
            'name' => 'terms',
            'type' => 'string',
            'description' => 'Retrieve a list of terms for a given taxonomy.',
            'source' => array('path' => '1'),
            'optional' => TRUE,
          ),
          array(
            'name' => 'page',
            'type' => 'string',
            'description' => 'The starting page number. Default is 1.',
            'source' => array('param' => 'page'),
            'optional' => TRUE,
          ),
          array(
            'name' => 'per_page',
            'type' => 'string',
            'description' => 'The number to retrieve per page. Default is 250.',
            'source' => array('param' => 'per_page'),
            'optional' => TRUE,
          ),
          array(
            'name' => 'fields',
            'type' => 'string',
            'description' => 'A comma separated list of fields to include.',
            'source' => array('param' => 'fields'),
            'optional' => TRUE,
          ),
        ),
      ),
      'create' => array(
        'help' => 'Creates a taxonomy',
        'file' => array(
          'type' => 'inc',
          'module' => 'skyword',
          'name' => 'resources/taxonomies',
        ),
        'callback' => '_skyword_taxonomies_create',
        'access callback' => 'skyword_access',
        'access arguments' => array('create taxonomy'),
        'access arguments append' => TRUE, 
        'args' => array(
          array(
            'name' => 'data',
            'type' => 'struct',
            'description' => 'The post data from the request',
            'source' => 'data',
            'optional' => FALSE,
          ),
          array(
            'name' => 'id',
            'type' => 'int',
            'description' => 'The identifier of the Taxonomy',
            'source' => array('path' => '0'),
            'optional' => TRUE,
          ),
          array(
            'name' => 'terms',
            'type' => 'string',
            'description' => 'Tells that we are going to create a new Taxonomy term.',
            'source' => array('path' => '1'),
            'optional' => TRUE,
          ),
        ),
      ),
    ),
    'authors' => array(
      'index' => array(
        'help' => 'Returns the index of Authors.',
        'file' => array(
          'type' => 'inc', 
          'module' => 'skyword', 
          'name' => 'resources/authors'
        ),
        'callback' => '_skyword_authors_index',
        'access callback' => '_skyword_access',
        'access arguments' => array('index authors'),
        'access arguments append' => TRUE,
        'args' => array(
          array(
            'name' => 'page',
            'type' => 'int',
            'description' => 'Starting page.',
            'source' => array('path' => 0),
            'optional' => TRUE,
          ),
          array(
            'name' => 'per_page',
            'type' => 'int',
            'description' => 'The​ ​number​ ​to​ ​retrieve​ ​per​ ​page.​ ​​ ​Default is​ ​250.',
            'source' => array('path' => 0),
            'optional' => TRUE,
          ),
        ),
      ),
      'retrieve' => array(
        'help' => 'Returns the index of Authors.',
        'file' => array(
          'type' => 'inc', 
          'module' => 'skyword', 
          'name' => 'resources/authors'
        ),
        'callback' => '_skyword_authors_get',
        'access callback' => '_skyword_access',
        'access arguments' => array('retrieve author'),
        'access arguments append' => TRUE,
        'args' => array(
          array(
            'name' => 'id',
            'type' => 'int',
            'description' => 'The unique id of the author.',
            'source' => array('path' => 0),
            'optional' => FALSE
          )
        ),
      ),
      'create' => array(
        'help' => 'Create an Author',
        'file' => array(
          'type' => 'inc',
          'module' => 'skyword',
          'name' => 'resources/authors',
        ),
        'callback' => '_skyword_authors_create',
        'access callback' => '_skyword_access',
        'acces arguments' => array('create author'),
        'access arguments append' => TRUE,
      ),
      'update' => array(
        'help' => 'Update an Author',
        'file' => array(
          'type' => 'inc',
          'module' => 'skyword',
          'name' => 'resources/authors',
        ),
        'callback' => '_skyword_authors_update',
        'access calback' => '_skyword_access',
        'access arguments' => array('update author'),
        'access arguments append' => TRUE,
      ),
    ),
    'posts' => array(
      'index' => array(
        'help' => 'Get the index of Posts',
        'file' => array(
          'type' => 'inc',
          'module' => 'skyword',
          'name' => 'resources/posts',
        ),
        'callback' => '_skyword_posts_index',
        'access callback' => '_skyword_access',
        'access arguments' => array('index posts'),
        'access arguments append' => TRUE,
      ),
      'retrieve' => array(
        'help' => 'Get a specific post',
        'file' => array(
          'type' => 'inc',
          'module' => 'skyword',
          'name' => 'resources/posts',
        ),
        'callback' => '_skyword_posts_retrieve',
        'access callback' => '_skyword_access',
        'access arguments' => array('retrieve post'),
        'access arguments append' => TRUE,
      ),
      'create' => array(
        'help' => 'Create a post',
        'file' => array(
          'type' => 'inc',
          'module' => 'skyword',
          'name' => 'resoruces/posts',
        ),
        'callback' => '_skyword_posts_crete',
        'access callback' => '_skyword_access',
        'access arguments' => array('create post'),
        'access arguments append' => TRUE,
      ),
      'update' => array(
        'help' => 'Update a post',
        'file' => array(
          'type' => 'inc',
          'module' => 'skyword',
          'name' => 'resources/posts',
        ),
        'callback' => '_skyword_posts_update',
        'access callback' => '_skyword_access',
        'access arguments' => array('update post'),
        'access arguments append' => TRUE,
      ),
    ),
    'media' => array(
      'index' => array(
        'help' => 'Get the index of medias',
        'file' => array(
          'type' => 'inc',
          'module' => 'skyword',
          'name' => 'resources/media',
        ),
        'callback' => '_skyword_medias_index',
        'access callback' => '_skyword_access',
        'access arguments' => array('index medias'),
        'access arguments append' => TRUE,
      ),
      'retrieve' => array(
        'help' => 'Retrieve a specific media',
        'file' => array(
          'type' => 'inc',
          'module' => 'skyword',
          'name' => 'resources/media',
        ),
        'callback' => '_skyword_medias_retrieve',
        'access callback' => '_skyword_access',
        'access arguments' => array('retrieve media'),
        'access arguments append' => TRUE,
      ),
      'create' => array(
        'help' => 'Create a media',
        'file' => array(
          'type' => 'inc',
          'module' => 'skyword',
          'name' => 'resources/media',
        ),
        'callback' => '_skyword_medias_create',
        'access callback' => '_skyword_access',
        'access arguments' => array('create media'),
        'access arguments append' => TRUE,
      ),
      'update' => array(
        'help' => 'Update a media',
        'file' => array(
          'type' => 'inc',
          'module' => 'skyword',
          'name' => 'resources/media',
        ),
        'callback' => '_skyword_medias_update',
        'access callback' => '_skyword_access',
        'access arguments' => array('update media'),
        'access arguments append' => TRUE,
      ),
    ),
    'content-types' => array(
      'index' => array(
        'help' => 'Return index of content types',
        'file' => array(
          'type' => 'inc',
          'module' => 'skyword',
          'name' => 'resources/content_types',
        ),
        'callback' => '_skyword_content_types_index',
        'access callback' => '_skyword_access',
        'access arguments' => array('index content types'),
        'access arguments append' => TRUE,
      ),
      'retrieve' => array(
        'help' => 'Retrieve a specific content type',
        'file' => array(
          'type' => 'inc',
          'module' => 'skyword',
          'name' => 'resources/content_types',
        ),
        'callback' => '_skyword_content_types_retrieve',
        'access callback' => '_skyword_access',
        'access arguments' => array('retrieve content type'),
        'access arguments append' => TRUE,
      ),
      'create' => array(
        'help' => 'Create a content type',
        'file' => array(
          'type' => 'inc',
          'module' => 'skyword',
          'name' => 'resources/content_types',
        ),
        'callback' => '_skyword_content_types_create',
        'access callback' => '_skyword_access',
        'access arguments' => array('create content type'),
        'access arguments append' => TRUE,
      ),
      'update' => array(
        'help' => 'Update a content type',
        'file' => array(
          'type' => 'inc',
          'module' => 'skyword',
          'name' => 'resources/content_types',
        ),
        'callback' => '_skyword_content_types_update',
        'access callback' => '_skyword_access',
        'access arguments' => array('update content type'),
        'access arguments append' => TRUE,
      ), // Not listed but maybe this is not needed.
    ),
  );
}

/**
 * Access callback check for Skyword API Services.
 */
function _skyword_access($op, $args) {
  global $user;
  $access = FALSE;

  switch($op) {
    case 'view version':
      $access = TRUE;

      break;

    case 'retrieve token':
      $access = TRUE;

      break;
  }

  return $access;
}

