<?php

/**
 * @file
 * Contains skyword.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function skyword_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the skyword module.
    case 'help.page.skyword':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('REST API for Skyword') . '</p>';
      return $output;

    default:
  }
}
